version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=nestjs_user
      - DB_PASSWORD=nestjs_password
      - DB_DATABASE=nestjs_db
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: nestjs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: