apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: lucky-numbers
spec:
  replicas: 2  # Reduced from 3 to be more resource-friendly
  selector:
    matchLabels:
      app: lucky-numbers
  template:
    metadata:
      labels:
        app: lucky-numbers
    spec:
      containers:
      - name: app
        image: daothevinh123/lucky_numbers:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            memory: "256Mi"  # Reduced for better scheduling
            cpu: "250m"
          requests:
            memory: "128Mi"  # Reduced for better scheduling
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60  # Increased delay
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30  # Increased delay
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: lucky-numbers
spec:
  selector:
    app: lucky-numbers
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer