# PostgreSQL Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "nestjs_db"
        - name: POSTGRES_USER
          value: "nestjs_user"
        - name: POSTGRES_PASSWORD
          value: "nestjs_password"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
# Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: lucky-numbers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lucky-numbers
  template:
    metadata:
      labels:
        app: lucky-numbers
    spec:
      containers:
      - name: app
        image: daothevinh123/lucky_numbers:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # Database connection environment variables
        - name: DB_HOST
          value: "postgres-service"  # This points to the PostgreSQL service
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "nestjs_user"
        - name: DB_PASSWORD
          value: "nestjs_password"
        - name: DB_DATABASE
          value: "nestjs_db"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        # Add health checks after database is working
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120  # Wait longer for DB connection
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
---
# Application Service
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: lucky-numbers
spec:
  selector:
    app: lucky-numbers
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer