name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        env:
          DOCKER_REPO: daothevinh123/lucky_numbers
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          docker push $DOCKER_REPO:$IMAGE_TAG
          docker tag $DOCKER_REPO:$IMAGE_TAG $DOCKER_REPO:latest
          docker push $DOCKER_REPO:latest

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name lucky-number --region ap-southeast-1

      - name: Deploy to EKS
        run: |
          # Apply deployment
          kubectl apply -f k8s/deployment.yaml
          
          # Update image to trigger rollout
          kubectl set image deployment/app app=daothevinh123/lucky_numbers:${{ github.sha }}
          
          # Show current status before waiting
          echo "=== Current Deployment Status ==="
          kubectl get deployment app -o wide
          kubectl get pods -l app=lucky-numbers -o wide
          
          # Check events for any issues
          echo "=== Recent Events ==="
          kubectl get events --sort-by='.lastTimestamp' | tail -10
          
          # Wait for rollout with longer timeout
          kubectl rollout status deployment/app --timeout=600s
          
          # Final status
          echo "=== Final Status ==="
          kubectl get pods -l app=lucky-numbers -o wide
          kubectl describe deployment app