name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        env:
          DOCKER_REPO: daothevinh123/lucky_numbers
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          docker push $DOCKER_REPO:$IMAGE_TAG
          docker tag $DOCKER_REPO:$IMAGE_TAG $DOCKER_REPO:latest
          docker push $DOCKER_REPO:latest

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name lucky-number --region ap-southeast-1

      - name: Deploy to EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Update the deployment YAML with the new image tag
          sed -i "s|daothevinh123/lucky_numbers:latest|daothevinh123/lucky_numbers:${IMAGE_TAG}|g" k8s/deployment.yaml
          
          # Apply deployment
          kubectl apply -f k8s/deployment.yaml
          
          # Show current status
          echo "=== Current Deployment Status ==="
          kubectl get deployment app -o wide
          kubectl get pods -l app=lucky-numbers -o wide
          
          # Check recent events
          echo "=== Recent Events ==="
          kubectl get events --sort-by='.lastTimestamp' | tail -10
          
          # Wait for rollout to complete
          echo "=== Waiting for rollout to complete ==="
          kubectl rollout status deployment/app --timeout=300s
          
          # Get final status
          echo "=== Final Status ==="
          kubectl get pods -l app=lucky-numbers -o wide
          kubectl get service app-service
          
          # Get logs from new pods
          echo "=== Application Logs ==="
          kubectl logs -l app=lucky-numbers --tail=20